### ISSUE TITLE
[BUG] Bettercap never seen as "available"

### ISSUE THREAD

**Issue by TheKayThatWasOrange** [aluminum-ice/pwnagotchi#71]
Flashed most recent image with balenaEtcher to a brand new card going into a brand new Pi0W.

Added `config.toml` just to set the whitelist and Waveshare display options. Defaults remain in place everywhere else. 

Everything boots and runs just fine but nothing meaningful ever happens because this goes on forever (no clock so the dates are all completely wrong):

```
[2023-05-03 03:18:50,137] [INFO] Session-stats plugin loaded.
[2023-05-03 03:18:50,144] [INFO] [update] plugin loaded.
[2023-05-03 03:18:50,150] [INFO] grid plugin loaded.
[2023-05-03 03:18:50,154] [INFO] [led] plugin loaded for /sys/class/leds/led0/brightness
[2023-05-03 03:18:50,226] [WARNING] ui.fps is 0, the display will only update for major changes
[2023-05-03 03:18:50,228] [INFO] initializing waveshare v3 display
[2023-05-03 03:19:02,651] [INFO] pwnagotchi@82fc514938787eb557982bd1ba1a509900a1b5b9114d7729fae6e77389b315c2 (v1.7.9)
[2023-05-03 03:19:02,663] [INFO] entering auto mode ...
[2023-05-03 03:19:02,704] [INFO] [ai] bootstrapping dependencies ...
[2023-05-03 03:19:02,788] [INFO] waiting for bettercap API to be available ...
[2023-05-03 03:19:03,347] [INFO] web ui available at http://0.0.0.0:8080/
[2023-05-03 03:19:03,864] [INFO] waiting for bettercap API to be available ...
[2023-05-03 03:19:07,451] [INFO] waiting for bettercap API to be available ...
[2023-05-03 03:19:12,589] [INFO] waiting for bettercap API to be available ...
[2023-05-03 03:19:13,675] [INFO] waiting for bettercap API to be available ...
[2023-05-03 03:19:14,721] [INFO] waiting for bettercap API to be available ...
```

The only errors I can see preceding this output in the logs pertain to a lack of internet connectivity when `urllib3` calls are made. None of the bridging scripts I've found actually accomplish anything in any current version of MacOS so I have no idea if things would succeed if `urllib3` was able to connect to something. They do not seem to be directly related to `bettercap` so my guess is nothing would change:

```
[2023-05-03 03:54:38,656] [ERROR] error while reading pwngrid data
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

I have verified that the default passwords are still in use in all the various config files everywhere and that I do have a `wlan0` interface. I cannot load any kind of web interface for bettercap but I also have no idea how I'm meant to go about doing this. My best guess based on what's in the default config is to try to load port 8081 on the device's IP but this is refused as nothing is listening there. 8080 works fine. 

Ports and processes:

```
$ sudo netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      443/python3         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      466/sshd            
tcp6       0      0 :::22                   :::*                    LISTEN      466/sshd            
udp        0      0 0.0.0.0:33130           0.0.0.0:*                           450/avahi-daemon: r 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           450/avahi-daemon: r 
udp6       0      0 :::34155                :::*                                450/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                450/avahi-daemon: r 
```

```
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.9  1.6  32472  7876 ?        Ss   09:18   0:12 /sbin/init
root         2  0.0  0.0      0     0 ?        S    09:18   0:00 [kthreadd]
root         6  0.0  0.0      0     0 ?        I<   09:18   0:00 [mm_percpu_wq]
root         7  0.0  0.0      0     0 ?        S    09:18   0:00 [rcu_tasks_rude_]
root         8  0.0  0.0      0     0 ?        S    09:18   0:00 [rcu_tasks_trace]
root         9  0.1  0.0      0     0 ?        S    09:18   0:01 [ksoftirqd/0]
root        10  0.0  0.0      0     0 ?        S    09:18   0:00 [kdevtmpfs]
root        11  0.0  0.0      0     0 ?        I<   09:18   0:00 [netns]
root        13  0.0  0.0      0     0 ?        S    09:18   0:00 [kauditd]
root        14  0.0  0.0      0     0 ?        I    09:18   0:00 [kworker/0:2-cgroup_destroy]
root        15  0.0  0.0      0     0 ?        S    09:18   0:00 [khungtaskd]
root        16  0.0  0.0      0     0 ?        S    09:18   0:00 [oom_reaper]
root        17  0.0  0.0      0     0 ?        I<   09:18   0:00 [writeback]
root        18  0.0  0.0      0     0 ?        S    09:18   0:00 [kcompactd0]
root        33  0.0  0.0      0     0 ?        I<   09:18   0:00 [kblockd]
root        34  0.0  0.0      0     0 ?        I<   09:18   0:00 [blkcg_punt_bio]
root        35  0.0  0.0      0     0 ?        S    09:18   0:00 [watchdogd]
root        36  0.0  0.0      0     0 ?        I<   09:18   0:00 [rpciod]
root        37  0.0  0.0      0     0 ?        I<   09:18   0:00 [kworker/u3:0-hci0]
root        38  0.0  0.0      0     0 ?        I<   09:18   0:00 [xprtiod]
root        39  0.0  0.0      0     0 ?        S    09:18   0:00 [kswapd0]
root        40  0.0  0.0      0     0 ?        I<   09:18   0:00 [nfsiod]
root        41  0.0  0.0      0     0 ?        I<   09:18   0:00 [iscsi_eh]
root        42  0.0  0.0      0     0 ?        I<   09:18   0:00 [iscsi_destroy]
root        43  0.0  0.0      0     0 ?        I<   09:18   0:00 [DWC Notificatio]
root        44  0.0  0.0      0     0 ?        S<   09:18   0:00 [vchiq-slot/0]
root        45  0.0  0.0      0     0 ?        S<   09:18   0:00 [vchiq-recy/0]
root        46  0.0  0.0      0     0 ?        S<   09:18   0:00 [vchiq-sync/0]
root        47  0.0  0.0      0     0 ?        I<   09:18   0:00 [zswap-shrink]
root        52  0.0  0.0      0     0 ?        I<   09:18   0:00 [mmc_complete]
root        53  0.0  0.0      0     0 ?        I<   09:18   0:01 [kworker/0:1H-mmc_complete]
root        54  0.0  0.0      0     0 ?        I<   09:18   0:00 [kworker/0:2H]
root        55  0.0  0.0      0     0 ?        S    09:18   0:00 [jbd2/mmcblk0p2-]
root        56  0.0  0.0      0     0 ?        I<   09:18   0:00 [ext4-rsv-conver]
root        57  0.0  0.0      0     0 ?        I<   09:18   0:00 [ipv6_addrconf]
root        88  0.2  1.4  35500  6852 ?        Ss   09:18   0:03 /lib/systemd/systemd-journald
root       113  0.1  0.7  18084  3900 ?        Ss   09:18   0:01 /lib/systemd/systemd-udevd
root       140  0.0  0.0      0     0 ?        S    09:18   0:00 [vchiq-keep/0]
root       152  0.0  0.0      0     0 ?        S    09:18   0:00 [spi0]
root       157  0.0  0.0      0     0 ?        S    09:18   0:00 [spi1]
root       195  0.0  0.0      0     0 ?        I<   09:18   0:00 [cfg80211]
root       215  0.0  0.0      0     0 ?        I<   09:18   0:00 [brcmf_wq/mmc1:0]
root       217  0.0  0.0      0     0 ?        S    09:18   0:00 [brcmf_wdog/mmc1]
root       227  0.0  0.0      0     0 ?        I    09:18   0:00 [kworker/u2:3-events_unbound]
systemd+   276  0.0  1.1  22368  5512 ?        Ssl  09:18   0:01 /lib/systemd/systemd-timesyncd
root       352  0.0  1.1  12996  5472 ?        Ss   09:18   0:01 /lib/systemd/systemd-logind
root       375  0.0  0.4   7928  2200 ?        Ss   09:18   0:00 /usr/sbin/cron -f
root       403  0.0  0.5   7780  2844 ?        Ss   09:18   0:00 bash /usr/bin/pwnagotchi-launcher
message+   425  0.1  0.6   6528  3368 ?        Ss   09:18   0:02 /usr/bin/dbus-daemon --system --address=systemd:
root       428  0.0  0.2  27636  1352 ?        SLsl 09:18   0:00 /usr/sbin/rngd -r /dev/hwrng
root       443  5.6  8.4 175228 41112 ?        Sl   09:18   1:13 /usr/bin/python3 /usr/local/bin/pwnagotchi --man
root       444  0.0  0.7  24592  3632 ?        Ssl  09:18   0:00 /usr/sbin/rsyslogd -n -iNONE
avahi      450  0.0  0.5   5748  2888 ?        Ss   09:18   0:00 avahi-daemon: running [pwnagotchi.local]
avahi      457  0.0  0.3   5748  1536 ?        S    09:18   0:00 avahi-daemon: chroot helper
root       466  0.0  1.1  10672  5572 ?        Ss   09:18   0:00 /usr/sbin/sshd -D
root       472  0.0  0.3  20496  1480 ?        Ssl  09:18   0:00 /usr/sbin/epd_fuse --panel=2.0 -o allow_other -o
root       486  0.0  0.3   4288  1700 tty1     Ss+  09:18   0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
root       512  0.0  0.1   2120   608 ?        S    09:18   0:00 /usr/bin/hciattach /dev/serial1 bcm43xx 3000000 
root       513  0.0  0.0      0     0 ?        I<   09:18   0:00 [kworker/u3:2-hci0]
root       522  0.0  1.2  12184  6144 ?        Ss   09:18   0:00 sshd: pi [priv]
root       532  0.0  0.9   9504  4404 ?        Ss   09:18   0:00 /usr/lib/bluetooth/bluetoothd --noplugin=sap
pi         595  0.0  1.4  14680  7248 ?        Ss   09:18   0:00 /lib/systemd/systemd --user
pi         596  0.0  0.6  16596  3328 ?        S    09:18   0:00 (sd-pam)
pi         610  0.0  0.8  12184  4100 ?        S    09:18   0:00 sshd: pi@pts/0
pi         611  0.0  0.7   8464  3704 pts/0    Ss   09:18   0:00 -bash
root      1795  0.0  0.0      0     0 ?        I    09:28   0:00 [kworker/u2:0]
root      2093  0.1  0.0      0     0 ?        I    09:30   0:00 [kworker/0:0-events_power_efficient]
root      2448  0.0  0.0      0     0 ?        I    09:32   0:00 [kworker/0:3-cgroup_destroy]
root      2887  0.0  0.0      0     0 ?        I<   09:36   0:00 [kworker/0:0H]
root      2950  0.0  0.0      0     0 ?        I    09:36   0:00 [kworker/u2:1-events_unbound]
root      3221  0.1  0.0      0     0 ?        I    09:38   0:00 [kworker/0:1-events]
pi        3431  0.0  0.5   9768  2480 pts/0    R+   09:40   0:00 ps aux
```

Sure seems like bettercap isn't running but I have no idea why.

**Comment by TheKayThatWasOrange** [comment]
Further spelunking reveals a missing `mon0` interface which suggests a required driver is missing from this image. Does that mean this board is too old? Too new? Why is logging useful information in an obvious place so difficult for the open source kids to grasp?

**Comment by TheKayThatWasOrange** [comment]
I'm just using the official distribution instead. No idea why I was told to use this one but I'm not going to listen to that person anymore.
